### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Bang1338** [yangman946/MIDI-to-Thirty-Dollar-Website-#1]
cmd crashed when starting main.py

**Comment by yangman946** [comment]
Hi, can you be a little more specific?
Was there a crash error? 
Have you tried running main.py as a command in cmd? e.g., `python main.py`

**Comment by yangman946** [comment]
Added a batch file in commit [a6e9abb](https://github.com/yangman946/MIDI-to-Thirty-Dollar-Website-/commit/a6e9abb08a696399b429d1f7416142602392aafc). Closing now due to inactivity.
